apiVersion: v1
kind: Service
metadata:
  name: store-products
spec:
  selector:
    app: store-products
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# after creating service, create another pod --> kubectl run busybox --image=busybox
# go into this pod ---> kubectl exec busybox -- curl -s store-products
# now you can see that you are able to connect the content via the service      