apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproweb
  labels:
    app: vproweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproweb
  template:
    metadata:
      labels:
        app: vproweb
    spec:
      containers:
      - name: vproweb
        image: furkanalp/vprofileweb
        resources:
        ports:
        - containerPort: 80       
---
apiVersion: v1
kind: Service
metadata:
  name: vproweb
spec:
  type: NodePort
  selector:
    app: vproweb
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001