apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-voll
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: ""
    fsType: ext4

# kubectl get pv
# kubectl delete pv pv-voll