apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            key: username
            name: mysecret
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: mysecret
      # - name: SECRET_USERNAME
      #   value: admin
      # - name: SECRET_PASSWORD
      #   value: 1f2d1e2e67df
    resources:

  restartPolicy: Never