kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-standard
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer # will delay the binding and provisioning of a PersistentVolume until a Pod using the PersistentVolumeClaim is created.
parameters:
  type: gp2
  fsType: ext4  