# ------- >> kubectl describe node node01 | grep -i taints
# ------- >> kubectl taint nodes node01 spray=mortein:NoSchedule #(key=value:tainttype)


apiVersion: v1
kind: Pod
metadata:
  name: bee
spec:
  containers:
  - image: nginx
    name: bee
  tolerations:
  - key: spray
    value: mortein
    effect: NoSchedule
    operator: Equal

# ----- >> kubectl taint nodes controlplane node-role.kubernetes.io/control-plane:NoSchedule- # (untaint)    