apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: clarusway/probes
    resources:
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
---
kind: Service
apiVersion: v1
metadata:
  name: liveness-svc
spec:
  selector:
    test:  liveness
  type: NodePort
  ports:
  - port:  80
    targetPort:  80
    nodePort: 30001     
