apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: httpd
spec:
  containers:
  - name: httpd
    image: httpd:2.4
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /test
        name:  emptydir-test
      - mountPath: "/usr/local/apache2/htdocs/"
        name: pv-storage
  volumes:
  - name: emptydir-test
    emptyDir: {}
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pv-claim  